instrumentation:
    root: ./src
    excludes: 
        - '**/*.spec.js'
        - 'authorisation/**/*.js'
        - 'api/**/*router.js'
        - 'api/**/*controller.js'
        - 'routing/**/*.js'
        - 'app.js'
        - 'utils/mysql/**/*.js'
reporting:
    dir: ./coverage_unit
checks:
    global:
        statements: 95
        lines: 95
        branches: 95
        functions: 100 
